Support for WebGL2 and GLSL 3.0 shaders.
heremaps/harp.gl pull request #1874
Opened 2020-09-25 00:14 UTC by J-Rojas

Commit to close #1575 

Determine WebGL2 support via canvas capabilities via MapView
Use new glslVersion setting (as of Three@0.120) in ShaderMaterials to support GLSL 3.0 features.

Signed-off-by: Jose Rojas <jrojas@redlinesolutions.co>

2020-09-25 01:24 UTC, J-Rojas commented
Unfortunately I don't have much time to fix these tests. The code works well for me. If anyone would like to address the intergration tests, I'd appreciate it.

2020-09-25 06:34 UTC, nzjony commented
@harpgl-bot retest this please

2020-09-25 10:19 UTC, atomicsulfate commented on @here/harp-materials/lib/EdgeMaterial.ts
> +        }
If we set THREE.ShaderMaterialParameters' glslVersion directly in function "createMaterial" instead, then we don't have to repeat the same logic for every material derived from THREE.RawShaderMaterial. It's also easy to forget adding doing this whenever we add a new material.

"createMaterial" can get as parameter the renderer capabilities and set the glsl version for instances of THREE.RawShaderMaterial when the renderer is WebGL2.

2020-09-25 10:30 UTC, atomicsulfate commented on @here/harp-text-canvas/lib/TextCanvas.ts
> +            });
Same here, just pass the renderer capabilities to createSdfTextMaterial and set there directly the THREE.ShaderMaterialParameters' glslVersion. That way you don't need to repeat the same logic below.

Unfortunately, the same code will have to be duplicated in createMaterial and createSdfTextMaterial, cause harp-text-canvas is meant to be a standalone module.

2020-09-25 10:32 UTC, atomicsulfate requested changes
I'd rather move the glsl version handling to the create material functions, please have a look at my comments.

2020-09-25 10:54 UTC, atomicsulfate commented on @here/harp-mapview/lib/MapView.ts
> +
This is a too low-level detail for MapView's interface. We try to move away from using MapView's as a facade for lower level interfaces.
You can access the renderer capabilities doing "mapView.renderer.capabilities", see my other comments.

2020-10-14 10:34 UTC, nzjony commented
Closing, because this was superseded by: https://github.com/heremaps/harp.gl/pull/1887

2020-10-14 10:34 UTC, closed without merging