HARP-13055: Add individual TextElementStates for line markers
heremaps/harp.gl pull request #1998
Opened 2020-12-01 17:53 UTC by StefanDachwitz

Signed-off-by: stefan.dachwitz <stefan.dachwitz@here.com>

Thank you for contributing to harp.gl!

Before requesting a pull request, please remember to check the following documents:
* [contribution guidelines](https://github.com/heremaps/harp.gl/blob/master/CONTRIBUTING.md)
* [coding style](https://github.com/heremaps/harp.gl/blob/master/CODINGSTYLE.md)

If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember to add tests for it.

# CI Check

Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps and someone from our team will take a look and help if needed!

And please do not forget to sign-off your commit! You can read more about DCO [here](https://julien.ponge.org/blog/developer-certificate-of-origin-versus-contributor-license-agreements/). But, in short, you just need to use `git commit -s` or append `--signoff` when you are committing to the repo.

Happy contributing!

2020-12-02 09:58 UTC, atomicsulfate commented on @here/harp-mapview/lib/text/TextElementState.ts
> +    private m_iconRenderState?: RenderState;
Doc needs update.

2020-12-02 10:29 UTC, atomicsulfate commented on @here/harp-mapview/lib/text/TextElementState.ts
> +}
To make it simpler, we can use TextElementState class for line markers as well and just pass and optional index to the constructor.
Then change the position getter to use the index if defined.

2020-12-02 10:30 UTC, atomicsulfate requested changes
Have a look at the simplification I suggest.
Better also double check any performance impact by running the macbook perf tests.

2020-12-02 14:14 UTC, StefanDachwitz commented
macbook tests please

2020-12-03 08:46 UTC, atomicsulfate approved these changes

2020-12-03 08:49 UTC, merged