HARP-14417: fix picking of polygon outlines
heremaps/harp.gl pull request #2165
Opened 2021-04-08 16:49 UTC by oleksmarkh

This PR fixes picking at polygonal outlines for the `fill` technique.

Before the fix:

<img width="400" alt="picking example" src="https://user-images.githubusercontent.com/2470363/114062030-b8a56080-989f-11eb-8dd0-78d643934e23.png">

* Expected result: when an outline is picked, all resulting objects (belonging to a given datasource) contain `.featureId` and `.userData` derived from original GeoJSON features that were used to render both `Mesh` and `LineSegments` objects.
* Actual result: while for `Mesh` objects results are correct (underlying polygons), for `LineSegments` it's always the first polygon of a given tile that's being returned instead. E.g. on the screenshot above, "Piemonte" is returned instead of "Abruzzo".

Reason:

<img width="251" alt="faceIndex value" src="https://user-images.githubusercontent.com/2470363/114064014-e2f81d80-98a1-11eb-97fb-762b55b1a87b.png">

`PickHandler` was comparing `.faceIndex` with `undefined` when deciding whether to take `.faceIndex * 3` or `.index` in order to recognise the proper feature. In case of `LineSegments` it's `null`, as that's the default value coming from THREE's [`.intersectObject()`](https://threejs.org/docs/#api/en/core/Raycaster.intersectObject).

2021-04-09 08:17 UTC, atomicsulfate requested changes
I know there's no PickHandler unit test, part is my fault since I changed this class a lot. So far we've been testing picking at a functional test "MapViewPickingTest.ts". But I think this class needs unit testing.
Could you please create one? So far it's enough to verify what you fixed, we'll add further coverage progressively.
Looks like the setup won't be straightforward. We can have a fake mapView with a single tile whose bbox must be intersected by the rayCaster's ray.
Then we could fake the rayCaster's (which is created in raycasterFromScreenPoint) intersectObjects() so that it returns the intersections that we want to test.

2021-04-13 08:43 UTC, oleksmarkh commented
@atomicsulfate, I've added two test cases ensuring the `.faceIndex` and `.index` lookups. The test setup is relying on minimal fake `MapView` substitute object (with a single fake rendered tile). I had to use the following combination of stubs in order to provide the test data:

```js
beforeEach(function () {
    ... // instantiating "PickHandler"
});

describe("#intersectMapObjects", function () {
    let raycasterFromScreenPointStub: sinon.SinonStub<[x: number, y: number], THREE.Raycaster>;

    beforeEach(function () {
        raycasterFromScreenPointStub = sinon.stub(pickHandler, "raycasterFromScreenPoint");
    });

    it("collects results for objects based on '.faceIndex' of intersection", function () {
        // these two stubs are defined inside test cases because
        // picking logic is tested against a combination of input coords and indexing data
        raycasterFromScreenPointStub.callsFake((x: number, y: number) => {
            // stubbing a real "Raycaster" instance
            const raycaster = raycasterFromScreenPointStub.wrappedMethod.call(pickHandler, x, y);
            sinon
                .stub(raycaster, "intersectObjects")
                .callsFake((objects, recursive, target: THREE.Intersection[] = []) => {
                    // test data, containing the index
                    target.push({...});
                });
            return raycaster;
        });

        const results = pickHandler.intersectMapObjects(467, 279);

        // checking for ".featureId" and ".userData"
        expect(...);
    });
});
```

2021-04-13 14:25 UTC, oleksmarkh commented
rebase please

2021-04-14 09:08 UTC, atomicsulfate approved these changes

2021-04-14 09:16 UTC, merged